name : "Postman Collection Workflow"

on :
  push :
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 07 * * 1-5

jobs:
  performing-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: installing node js and npm
        uses: actions/setup-node@v3.9.1

      - name: installing npm and newman with htmlextra
        run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

      - name: checkout repository to runner
        uses: actions/checkout@v5.0.0

      - name: running collection
        run: |
              newman run in-warrenty-flow.postman_collection.json \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,htmlextra

      - name: saving newman report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          path: newman/*.html
        

      - name: Creating github Page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: newman/
        
              

              

       
  
