name : "Postman Collection Workflow"
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * #08 am morning
    - cron: 00 01 * * 1-5 # Monday to Friday at 06:30 Pm Ist

jobs:
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      - name : checkout the code
        uses: actions/checkout@v5.0.0
        
      - name : install node js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'
          
      - name : install newman and reporters
        run : | # Multiline command
              npm install -g newman
              npm install -g newman-reporter-htmlextra

      - name : Running postman collection
        run : | 
              newman run in-warrenty-flow.postman_collection.json \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli, htmlextra \
              --reporter-htmlextra-export newman/report.html


      - name : Saving Newman Report
        if : always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name : Newman Report
          path : newman/*.html

        
        
      
      
  
