name : "Postman Collection Workflow"

on :
  push :
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 07 * * 1-5

jobs:
  performing-jobs:
    runs-on: ubuntu-latest #label-github-ec2-runer
    steps:
      - name: checkout repository to runner
        uses: actions/checkout@v5.0.0

        
      - name: installing node js and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: installing npm and newman with htmlextra
        run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra



      - name: running collection
        run: |
              newman run in-warrenty-flow.postman_collection.json \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,htmlextra \
              --reporter-htmlextra-export ./newman/index.html

      - name: saving newman report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          path: newman/*.html
        

      - name: Creating github Page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: newman/

      - name: Sending mail to recipents
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Report for Phoneix apllication Flow
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: | 
                  Hi all , 
                  this is the testing Report email. We are not using the attachments: key here since it will attach 50MB of file that's
                  going to store inside Google Drive. But it's Maximum file attachment is 25 MB for email. Link to Workflow file is 
                  Link : https://vishalxxx.github.io/SDET/
          
          
          
              

              

       
  
